# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "HelloWorldFunctionJava"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[qa.deploy.parameters]
capabilities = "CAPABILITY_IAM"
STACK_NAME = "sam-test"
REGION = 'us-east-1'

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
STACK_NAME = 'sam-app'
REGION = 'us-east-2'

[default.package.parameters]

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
